# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170722_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsignal',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
